services:
  - type: web
    name: Ozonator Agents AA
    runtime: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: 'uvicorn main:app --host 0.0.0.0 --port $PORT'
    healthCheckPath: /health

  - type: web
    name: Ozonator Agents AZ
    runtime: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: 'uvicorn az_main:app --host 0.0.0.0 --port $PORT'
    healthCheckPath: /health

  - type: web
    name: Ozonator Agents AS
    runtime: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: 'uvicorn as_main:app --host 0.0.0.0 --port $PORT'
    healthCheckPath: /health

  - type: web
    name: Ozonator Agents AK
    runtime: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: 'uvicorn ak_main:app --host 0.0.0.0 --port $PORT'
    healthCheckPath: /health
